<?php

/**
 * @file
 */

use Drupal\node\Entity\Node;

/**
 * Implements hook_cron().
 */
function blog_cleanup_cron() {

  $one_year_ago = strtotime('-1 year');

  $query = \Drupal::entityTypeManager()->getStorage('node')->getQuery();
  $nids = $query
    ->condition('type', 'blogs')
    ->condition('status', 1)
    ->condition('uid', 0)
    ->condition('created', $one_year_ago, '<')
    ->execute();

  if (!empty($nids)) {
    $nodes = Node::loadMultiple($nids);
    foreach ($nodes as $node) {
      $node->delete();
    }
    \Drupal::logger('blog_cleanup')->notice('Deleted @count old guest blogs.', ['@count' => count($nodes)]);
  }
}
